failures
debug_callableNotUnique
| code/class_properties.py:7:5:7:18 | Function arg | Qualified function name 'Prop.arg' is not unique within its file. Please fix. |
| code/class_properties.py:12:5:12:25 | Function arg | Qualified function name 'Prop.arg' is not unique within its file. Please fix. |
| code/class_properties.py:17:5:17:18 | Function arg | Qualified function name 'Prop.arg' is not unique within its file. Please fix. |
pointsTo_found_typeTracker_notFound
| code/class_super.py:50:1:50:6 | ControlFlowNode for Attribute() | outside_def |
pointsTo_notFound_typeTracker_found
| code/class_more_mro2.py:18:9:18:21 | ControlFlowNode for Attribute() | A.foo |
| code/class_more_mro2.py:21:1:21:8 | ControlFlowNode for Attribute() | A.foo |
| code/class_more_mro.py:24:9:24:21 | ControlFlowNode for Attribute() | A.foo |
| code/class_more_mro.py:34:1:34:16 | ControlFlowNode for Attribute() | A.foo |
| code/class_subclass.py:66:1:66:15 | ControlFlowNode for Attribute() | D.some_method |
| code/class_subclass.py:72:1:72:15 | ControlFlowNode for Attribute() | C.some_method |
| code/class_super.py:43:9:43:21 | ControlFlowNode for Attribute() | A.bar |
| code/class_super.py:44:9:44:27 | ControlFlowNode for Attribute() | A.bar |
| code/class_super.py:63:1:63:18 | ControlFlowNode for Attribute() | A.foo |
| code/class_super.py:78:9:78:28 | ControlFlowNode for Attribute() | A.foo |
| code/class_super.py:81:1:81:12 | ControlFlowNode for Attribute() | C.foo_on_A |
| code/class_super.py:92:9:92:21 | ControlFlowNode for Attribute() | X.foo |
| code/class_super.py:97:9:97:21 | ControlFlowNode for Attribute() | X.foo |
| code/class_super.py:97:9:97:21 | ControlFlowNode for Attribute() | Y.foo |
| code/class_super.py:101:1:101:7 | ControlFlowNode for Attribute() | Z.foo |
| code/class_super.py:108:1:108:8 | ControlFlowNode for Attribute() | Y.foo |
| code/class_super.py:108:1:108:8 | ControlFlowNode for Attribute() | Z.foo |
| code/underscore_prefix_func_name.py:14:5:14:19 | ControlFlowNode for some_function() | some_function |
